### PR TITLE
Release 2020-05-17

### PR DESCRIPTION
**Pull request by FNSdev**
- Creating organizations
- Creating boards
- Sending organization invites
- Accepting / Declining organization invites
- Adding users to boards
- Removing users from organizations
- Removing users from boards
- 401 and 403 errors handling

https://gitrello.me

I have created a few test organizations, boards and invites (you will own one of them), so that you can test everything. Feel free to create more :)

### CODE REVIEW

**Comment by FNSdev** [comment]
@gmltA thanks for a feedback

> All invites disappeared from profile page after the first one was accepted.

Oops. I`ll check it.

> Board creation dialog displays nothing after I click "create". (although permission denied is correctly displayed when I try to create one in another organisation).

Can`t reproduce it :( 
Seems to work fine for me. Could you please provide more info?

> Boards URL (from organisation page) leads to 404.
Yea, its not implemented yet

> It is unclear what is gonna happen when we click on user on organisation page.

True, but I think i`ll keep it as it is for now. Is that OK?

**Comment by gmltA** [comment]
> Seems to work fine for me. Could you please provide more info?

I am just trying to create a new board. After I typed in board name and pressed button, board is created, but I see no visual feedback in dialog.

**Comment by FNSdev** [comment]
> I am just trying to create a new board. After I typed in board name and pressed button, board is created, but I see no visual feedback in dialog.

Oh I see. There is no feedback message when everything is successful by design :)
I can either add it, or just close modal window.

**Comment by gmltA** [comment]
> I can either add it, or just close modal window.

You can display status in a way you display errors but in green. A progress indicator would also be a good UX improvement.

**Comment by FNSdev** [comment]
The problem is that errors are displayed in <errors-list-component>. I guess I can just change it to be <messages-component> that will be able to display different type of messages (with different border colors).

Progress indicators are a great idea, but it will take me some time to add them.
I think that I should focus on boards and tickets, If I want to make everything work before my exam.
:-C

**Comment by gmltA** [comment]
Sure thing. That's not a vital feature)

**Pull request merged**
