### PR TITLE
Release 2020-05-25

### PR DESCRIPTION
**Pull request by FNSdev**
- Drag-n-Drop for tickets

Not production ready, because new priority for ticket is calculated on the client-side.
If more than 1 person will try to move/create tickets simultaneously, everything will break :(

I don`t know what to do with it. The only solution that I see (that won't be too difficult to implement) is calculating everything on the server side (except for ticket, after which dragged ticket should be placed) and refreshing board page. Yeah, its possible that "previous ticket" was moved, but it should not break anything ("not break" means that after refreshing board page everything will be sorted by priorities correctly, but ticket position might be different from what was expected)

https://gitrello.me

### CODE REVIEW

**Comment by FNSdev** [comment]
UPD. I have just realized, that current implementation is ok, because other ticket's priorities are updated on the server side independently. The only problem is that client side expects tickets to have priorities equal to their indexes in the tickets array.

**Comment by gmltA** [comment]
The best way here is to use websockets to update ticket positions in real-time. Some conflicts are possible, but it won't be too critical.

**Comment by FNSdev** [comment]
> The best way here is to use websockets

True, but as we discussed earlier, I don't have much experience with sockets yet. I should give it a try at some point for sure. 

> your personal experience with WebComponents

I feel like that is the right way to develop client-side applications but I also feel like I did not use their full potential. 

It turned out that my Components are tight to each other in some way and can not be reused a lot by their own. 

Shadow DOM is great, but it was very confusing for me, that styles from the light dom are not visible from it.  

I also think that everything that I did using Web Components can be replaced with some classes that generate HTML after adding some data to it. 

The most painful part of the whole process was updating some data in another component after something has happened. I know that different frameworks provide some sort of a data-binding mechanism that makes it a lot easier. Perhaps I should have done something similar instead of creating ugly callbacks (live-data / observable collections or smth like that).

Overall, I think that it is a nice way to encapsulate some business logic with markup and CSS, but should be used correctly.

P.S. I don't know why i did not use slots :roll_eyes: 
I tried to use 'setAttribute/getAttribute', but it requires object's serialization, which is not great in my opinion.
It was easier for me to pass parameters in component's constructor.

**Comment by gmltA** [comment]
Yep. Sums up general impression of components pretty much. Initially Google tried to build Polymer framework as a shim for things which are not yet available in WebComponents (such as data-binding, as you pointed out correctly), but unfortunately things are still hanging and we won't get full-fledged native replacement for third-party systems in the near future.

Still I see you designed architecture of your project very well using options available.

Thanks again and good luck!

**Pull request merged**
